# PBS configuration
queue: normalbw
project: x77
walltime: 05:00:00
jobname: access-om-025
ncpus: 1153
memory: 2000Gb

platform:
   nodesize: 28


laboratory: /short/v45/aph502/COSIMA/access-om

collate: true
collate_walltime: 4:00:00
collate_mem: 30GB
collate_ncpus: 4
collate_queue: express
collate_flags: -n4 -z -m -r

# Model configuration
model: access
submodels:
    - name: coupler
      model: oasis
      input: oasis_025
      ncpus: 0

    - name: atmosphere
      model: matm
      exe: matm_cice.exe
      input: jra55-0.8_025
      ncpus: 1

    - name: ocean
      model: mom
      exe: fms_ACCESS-OM.x
      input: 
            - mom
            # - iaf-sw21d
      ncpus: 960

    - name: ice
      model: cice
      exe: cice_access-om_1440x1080_192p.exe
      input: cice
      ncpus: 192


calendar:
    runtime:
        years: 0
        months: 3
        days: 0

    start:
        year: 1
        month: 1
        days: 1


# Misc
stacksize: unlimited

runlog: true

debug: false

ipm: 2.0.5
